version: '3'
services:
  nginx:
    image: nginx:1.24
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - automation_hub_network

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - db
      - backend
    networks:
      - automation_hub_network

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    networks:
      - automation_hub_network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: test
      POSTGRES_DB: automation_hub
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - automation_hub_network

volumes:
  db_data:

networks:
  automation_hub_network:
    driver: bridge
